### ISSUE TITLE
ipn 不能发送邮件

### ISSUE THREAD

**Issue by D-qing** [devzhi/ipn#1]
可以获取IP地址，却不能自动发送邮件，请问怎么处理？

**Comment by devzhi** [comment]
首先请确保您的邮箱信息配置正确，此外您可以将您邮件发送失败的相关输出贴出来。

**Comment by D-qing** [comment]
邮箱配置 没问题
![image](https://github.com/devzhi/ipn/assets/110857661/310079ee-4dc1-49dd-839b-9b12487e6338)

**Comment by D-qing** [comment]
# 设备名称
Device = "test device"
# SMTP服务器地址
SmtpHost = "smtp.qq.com"
# SMTP服务器端口
SmtpPort = 587
# 发件人地址
From = "51565779@qq.com"
# 发件人密码（部分供应商使用授权码，如QQ邮箱）
Password = "xjdkjilgbixbdidf"
# 收件人地址
To = ["51565779@qq.com"]
# 启用内置cron
EnableCron = false
# Cron表达式
CronExp = "*/5 * * * *"

**Comment by devzhi** [comment]
![test_result](https://github.com/devzhi/ipn/assets/10175583/4785eb2f-19a0-45c1-a921-5ba4ddf5e34e)
我这边用自己的QQ邮箱测试了一下是没有问题的，请您注意QQ邮箱的发件人密码需要使用授权码（登录QQ邮箱--设置--POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务内申请），请您确认您的配置信息正确并且网络畅通。
为了更快的与您取得联系并解决您的问题，我将尝试通过您共享的配置信息中的QQ号码与您取得联系。

**Comment by devzhi** [comment]
![image](https://github.com/devzhi/ipn/assets/10175583/2533e277-2a59-4d2f-adf0-ed5950d9ad9f)
因为您的隐私设置，我无法添加您为好友，请您先行测试，若仍无效请留下可以联系到您的联系方式。

**Comment by D-qing** [comment]
可以加我了 谢谢~~

**Comment by devzhi** [comment]
经过私下交流验证，发现配置文件存在两个问题：

1. 端口与示例配置文件不一致（465），未验证该端口是否可用
2. 配置文件从UTF-8 without BOM转变为了UTF-8 with bom，导致配置文件解析失败

![PixPin_2024-07-11_09-14-33](https://github.com/devzhi/ipn/assets/10175583/c32de2d7-c0e5-4375-8318-0cd7e5bba098)


解决方案：

1. 为用户提供了修改好的配置文件（修改端口与编码）
2. 发布新版本，在配置文件错误时予以报错

感谢使用~

**Comment by D-qing** [comment]
已经可以使用了，谢谢~~
