### ISSUE TITLE
一个建议~~

### ISSUE THREAD

**Issue by D-qing** [devzhi/ipn#2]
增加一个选项，如果IP无变化，也发送邮件~~

**Comment by devzhi** [comment]
感谢建议，会在近期添加该功能

**Comment by devzhi** [comment]
v1.3版本已发布，新增【总是发送邮件】功能
[https://github.com/devzhi/ipn/releases/tag/1.3](https://github.com/devzhi/ipn/releases/tag/1.3)

**Comment by D-qing** [comment]
谢谢~~
